// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OugAssistant_DB.Features;

#nullable disable

namespace OugAssistant_DB.Migrations
{
    [DbContext(typeof(PlanningDBContext))]
    [Migration("20250503233418_RemakeModel2")]
    partial class RemakeModel2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("TimeDay")
                        .HasColumnType("time");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("Task");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Event", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Mission", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Mission");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.RoutineTask", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<DateTime>("DoDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RoutineId");

                    b.HasDiscriminator().HasValue("RoutineTask");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Task", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.RoutineTask", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Goal", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
