// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OugAssistant_DB.Features;

#nullable disable

namespace OugAssistant_DB.Migrations
{
    [DbContext(typeof(PlanningDBContext))]
    [Migration("20250817195517_NewModel1")]
    partial class NewModel1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OugGoal");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("FinishedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OugTasks");

                    b.HasDiscriminator().HasValue("OugTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OugTaskGoal", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaskId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("OugTaskGoal");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugEvent", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OugEvent");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugMission", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("OugMission");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugRoutine", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime?>("LastFinished")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoutineDays")
                        .HasColumnType("int");

                    b.Property<string>("Routines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OugRoutine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugGoal", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.OugGoal", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugTask", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.OugTask", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OugTaskGoal", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.OugGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OugAssistant.Features.Planning.Model.OugTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugGoal", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugTask", b =>
                {
                    b.Navigation("Childs");
                });
#pragma warning restore 612, 618
        }
    }
}
