// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OugAssistant_DB.Features;

#nullable disable

namespace OugAssistant_DB.Migrations
{
    [DbContext(typeof(PlanningDBContext))]
    [Migration("20250504162314_RemakeModel5")]
    partial class RemakeModel5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OugGoal");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OugRoutine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("OugTasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("OugTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugEvent", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugMission", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Mission");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugRoutineTask", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.OugTask");

                    b.Property<DateTime>("RoutineDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RoutineId");

                    b.HasDiscriminator().HasValue("RoutineTask");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugTask", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.OugGoal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugRoutineTask", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.OugRoutine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.OugGoal", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
