// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OugAssistant_DB.Features;

#nullable disable

namespace OugAssistant_DB.Migrations
{
    [DbContext(typeof(PlanningDBContext))]
    [Migration("20250503151422_herencia")]
    partial class herencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goal", (string)null);
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.RoutineTask", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineTask", (string)null);
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Task");

                    b.HasDiscriminator<string>("TaskType").HasValue("Task");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.TaskHistory", b =>
                {
                    b.Property<DateTime>("FinishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskHistory", (string)null);
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Event", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Mission", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Mission");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.Routine", b =>
                {
                    b.HasBaseType("OugAssistant.Features.Planning.Model.Task");

                    b.Property<TimeOnly>("TimeDay")
                        .HasColumnType("time");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Routine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.RoutineTask", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("OugAssistant.Features.Planning.Model.TaskHistory", b =>
                {
                    b.HasOne("OugAssistant.Features.Planning.Model.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
